name: voco_case_study
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  auto_route: ^7.8.3
  kartal: ^3.5.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.2
  auto_route_generator: ^7.1.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
